package Akinita.project.Akinita.entities;

public enum facilities {
    AC, ELEVATOR, PARKING, GARDEN, FIREPLACE, POOL,STORAGE, ALARM, PAINTED, CLASSA1,CLASS2,CLASSB1,CLASSB2,CLASSC,CLASSD,CLASSE,CLASSZ,CLASSH
}
